application: vendladder
version: foos-22
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: jinja2
  version: latest

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /static
  static_dir: static

- url: /.*
  script: main.app

- url: /mgmt/.*
  script: main.app2
